repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: "v1.105.0"
    hooks:
      - id: terragrunt_fmt
      - id: terraform_fmt
        args:
         - --hook-config=--tf-path=tofu
      - id: terraform_tflint
        args:
         - --hook-config=--tf-path=tofu
      - id: terraform_validate
        args:
         - --hook-config=--tf-path=tofu
      - id: terragrunt_providers_lock
        args:
          - --hook-config=--tf-path=tofu
          - --hook-config=--mode=regenerate-lockfile-if-some-platform-missed
          - --args=-platform=darwin_arm64
          - --args=-platform=darwin_amd64
          - --args=-platform=linux_amd64
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=always-regenerate-lockfile
          - --hook-config=--mode=regenerate-lockfile-if-some-platform-missed
          - --hook-config=--tf-path=tofu
          - --args=-platform=darwin_arm64
          - --args=-platform=darwin_amd64
          - --args=-platform=linux_amd64
